// World country dial-code list for the phone country-code selector
// (create/edit client, profile — see `PhoneField.tsx`). Sénégal is pinned
// first (the app's home market, and the sensible default for a phone field
// left untouched), the rest are alphabetical by French name. Login/signup
// keep their own fixed "+221" split UI on purpose (that phone is the
// account's own auth-relevant number, always Senegalese by design) — this
// list is only for client/profile phone numbers, which can genuinely be
// any country.
export interface CountryDialCode {
  iso2: string;
  nameFr: string;
  dialCode: string;
}

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { iso2: 'SN', nameFr: 'Sénégal', dialCode: '221' },
  { iso2: 'AF', nameFr: 'Afghanistan', dialCode: '93' },
  { iso2: 'ZA', nameFr: 'Afrique du Sud', dialCode: '27' },
  { iso2: 'AL', nameFr: 'Albanie', dialCode: '355' },
  { iso2: 'DZ', nameFr: 'Algérie', dialCode: '213' },
  { iso2: 'DE', nameFr: 'Allemagne', dialCode: '49' },
  { iso2: 'AD', nameFr: 'Andorre', dialCode: '376' },
  { iso2: 'AO', nameFr: 'Angola', dialCode: '244' },
  { iso2: 'SA', nameFr: 'Arabie saoudite', dialCode: '966' },
  { iso2: 'AR', nameFr: 'Argentine', dialCode: '54' },
  { iso2: 'AM', nameFr: 'Arménie', dialCode: '374' },
  { iso2: 'AU', nameFr: 'Australie', dialCode: '61' },
  { iso2: 'AT', nameFr: 'Autriche', dialCode: '43' },
  { iso2: 'AZ', nameFr: 'Azerbaïdjan', dialCode: '994' },
  { iso2: 'BS', nameFr: 'Bahamas', dialCode: '1' },
  { iso2: 'BH', nameFr: 'Bahreïn', dialCode: '973' },
  { iso2: 'BD', nameFr: 'Bangladesh', dialCode: '880' },
  { iso2: 'BB', nameFr: 'Barbade', dialCode: '1' },
  { iso2: 'BE', nameFr: 'Belgique', dialCode: '32' },
  { iso2: 'BZ', nameFr: 'Belize', dialCode: '501' },
  { iso2: 'BJ', nameFr: 'Bénin', dialCode: '229' },
  { iso2: 'BT', nameFr: 'Bhoutan', dialCode: '975' },
  { iso2: 'BY', nameFr: 'Biélorussie', dialCode: '375' },
  { iso2: 'BO', nameFr: 'Bolivie', dialCode: '591' },
  { iso2: 'BA', nameFr: 'Bosnie-Herzégovine', dialCode: '387' },
  { iso2: 'BW', nameFr: 'Botswana', dialCode: '267' },
  { iso2: 'BR', nameFr: 'Brésil', dialCode: '55' },
  { iso2: 'BN', nameFr: 'Brunei', dialCode: '673' },
  { iso2: 'BG', nameFr: 'Bulgarie', dialCode: '359' },
  { iso2: 'BF', nameFr: 'Burkina Faso', dialCode: '226' },
  { iso2: 'BI', nameFr: 'Burundi', dialCode: '257' },
  { iso2: 'KH', nameFr: 'Cambodge', dialCode: '855' },
  { iso2: 'CM', nameFr: 'Cameroun', dialCode: '237' },
  { iso2: 'CA', nameFr: 'Canada', dialCode: '1' },
  { iso2: 'CV', nameFr: 'Cap-Vert', dialCode: '238' },
  { iso2: 'CF', nameFr: 'République centrafricaine', dialCode: '236' },
  { iso2: 'CL', nameFr: 'Chili', dialCode: '56' },
  { iso2: 'CN', nameFr: 'Chine', dialCode: '86' },
  { iso2: 'CY', nameFr: 'Chypre', dialCode: '357' },
  { iso2: 'CO', nameFr: 'Colombie', dialCode: '57' },
  { iso2: 'KM', nameFr: 'Comores', dialCode: '269' },
  { iso2: 'CG', nameFr: 'Congo-Brazzaville', dialCode: '242' },
  { iso2: 'CD', nameFr: 'Congo-Kinshasa', dialCode: '243' },
  { iso2: 'KP', nameFr: 'Corée du Nord', dialCode: '850' },
  { iso2: 'KR', nameFr: 'Corée du Sud', dialCode: '82' },
  { iso2: 'CR', nameFr: 'Costa Rica', dialCode: '506' },
  { iso2: 'CI', nameFr: "Côte d'Ivoire", dialCode: '225' },
  { iso2: 'HR', nameFr: 'Croatie', dialCode: '385' },
  { iso2: 'CU', nameFr: 'Cuba', dialCode: '53' },
  { iso2: 'DK', nameFr: 'Danemark', dialCode: '45' },
  { iso2: 'DJ', nameFr: 'Djibouti', dialCode: '253' },
  { iso2: 'EG', nameFr: 'Égypte', dialCode: '20' },
  { iso2: 'AE', nameFr: 'Émirats arabes unis', dialCode: '971' },
  { iso2: 'EC', nameFr: 'Équateur', dialCode: '593' },
  { iso2: 'ER', nameFr: 'Érythrée', dialCode: '291' },
  { iso2: 'ES', nameFr: 'Espagne', dialCode: '34' },
  { iso2: 'EE', nameFr: 'Estonie', dialCode: '372' },
  { iso2: 'SZ', nameFr: 'Eswatini', dialCode: '268' },
  { iso2: 'US', nameFr: 'États-Unis', dialCode: '1' },
  { iso2: 'ET', nameFr: 'Éthiopie', dialCode: '251' },
  { iso2: 'FJ', nameFr: 'Fidji', dialCode: '679' },
  { iso2: 'FI', nameFr: 'Finlande', dialCode: '358' },
  { iso2: 'FR', nameFr: 'France', dialCode: '33' },
  { iso2: 'GA', nameFr: 'Gabon', dialCode: '241' },
  { iso2: 'GM', nameFr: 'Gambie', dialCode: '220' },
  { iso2: 'GE', nameFr: 'Géorgie', dialCode: '995' },
  { iso2: 'GH', nameFr: 'Ghana', dialCode: '233' },
  { iso2: 'GR', nameFr: 'Grèce', dialCode: '30' },
  { iso2: 'GT', nameFr: 'Guatemala', dialCode: '502' },
  { iso2: 'GN', nameFr: 'Guinée', dialCode: '224' },
  { iso2: 'GW', nameFr: 'Guinée-Bissau', dialCode: '245' },
  { iso2: 'GQ', nameFr: 'Guinée équatoriale', dialCode: '240' },
  { iso2: 'GY', nameFr: 'Guyana', dialCode: '592' },
  { iso2: 'HT', nameFr: 'Haïti', dialCode: '509' },
  { iso2: 'HN', nameFr: 'Honduras', dialCode: '504' },
  { iso2: 'HU', nameFr: 'Hongrie', dialCode: '36' },
  { iso2: 'MH', nameFr: 'Îles Marshall', dialCode: '692' },
  { iso2: 'SB', nameFr: 'Îles Salomon', dialCode: '677' },
  { iso2: 'IN', nameFr: 'Inde', dialCode: '91' },
  { iso2: 'ID', nameFr: 'Indonésie', dialCode: '62' },
  { iso2: 'IQ', nameFr: 'Irak', dialCode: '964' },
  { iso2: 'IR', nameFr: 'Iran', dialCode: '98' },
  { iso2: 'IE', nameFr: 'Irlande', dialCode: '353' },
  { iso2: 'IS', nameFr: 'Islande', dialCode: '354' },
  { iso2: 'IL', nameFr: 'Israël', dialCode: '972' },
  { iso2: 'IT', nameFr: 'Italie', dialCode: '39' },
  { iso2: 'JM', nameFr: 'Jamaïque', dialCode: '1' },
  { iso2: 'JP', nameFr: 'Japon', dialCode: '81' },
  { iso2: 'JO', nameFr: 'Jordanie', dialCode: '962' },
  { iso2: 'KZ', nameFr: 'Kazakhstan', dialCode: '7' },
  { iso2: 'KE', nameFr: 'Kenya', dialCode: '254' },
  { iso2: 'KG', nameFr: 'Kirghizistan', dialCode: '996' },
  { iso2: 'KI', nameFr: 'Kiribati', dialCode: '686' },
  { iso2: 'XK', nameFr: 'Kosovo', dialCode: '383' },
  { iso2: 'KW', nameFr: 'Koweït', dialCode: '965' },
  { iso2: 'LA', nameFr: 'Laos', dialCode: '856' },
  { iso2: 'LS', nameFr: 'Lesotho', dialCode: '266' },
  { iso2: 'LV', nameFr: 'Lettonie', dialCode: '371' },
  { iso2: 'LB', nameFr: 'Liban', dialCode: '961' },
  { iso2: 'LR', nameFr: 'Liberia', dialCode: '231' },
  { iso2: 'LY', nameFr: 'Libye', dialCode: '218' },
  { iso2: 'LI', nameFr: 'Liechtenstein', dialCode: '423' },
  { iso2: 'LT', nameFr: 'Lituanie', dialCode: '370' },
  { iso2: 'LU', nameFr: 'Luxembourg', dialCode: '352' },
  { iso2: 'MK', nameFr: 'Macédoine du Nord', dialCode: '389' },
  { iso2: 'MG', nameFr: 'Madagascar', dialCode: '261' },
  { iso2: 'MY', nameFr: 'Malaisie', dialCode: '60' },
  { iso2: 'MW', nameFr: 'Malawi', dialCode: '265' },
  { iso2: 'MV', nameFr: 'Maldives', dialCode: '960' },
  { iso2: 'ML', nameFr: 'Mali', dialCode: '223' },
  { iso2: 'MT', nameFr: 'Malte', dialCode: '356' },
  { iso2: 'MA', nameFr: 'Maroc', dialCode: '212' },
  { iso2: 'MU', nameFr: 'Maurice', dialCode: '230' },
  { iso2: 'MR', nameFr: 'Mauritanie', dialCode: '222' },
  { iso2: 'MX', nameFr: 'Mexique', dialCode: '52' },
  { iso2: 'FM', nameFr: 'Micronésie', dialCode: '691' },
  { iso2: 'MD', nameFr: 'Moldavie', dialCode: '373' },
  { iso2: 'MC', nameFr: 'Monaco', dialCode: '377' },
  { iso2: 'MN', nameFr: 'Mongolie', dialCode: '976' },
  { iso2: 'ME', nameFr: 'Monténégro', dialCode: '382' },
  { iso2: 'MZ', nameFr: 'Mozambique', dialCode: '258' },
  { iso2: 'MM', nameFr: 'Myanmar', dialCode: '95' },
  { iso2: 'NA', nameFr: 'Namibie', dialCode: '264' },
  { iso2: 'NR', nameFr: 'Nauru', dialCode: '674' },
  { iso2: 'NP', nameFr: 'Népal', dialCode: '977' },
  { iso2: 'NI', nameFr: 'Nicaragua', dialCode: '505' },
  { iso2: 'NE', nameFr: 'Niger', dialCode: '227' },
  { iso2: 'NG', nameFr: 'Nigeria', dialCode: '234' },
  { iso2: 'NO', nameFr: 'Norvège', dialCode: '47' },
  { iso2: 'NZ', nameFr: 'Nouvelle-Zélande', dialCode: '64' },
  { iso2: 'OM', nameFr: 'Oman', dialCode: '968' },
  { iso2: 'UG', nameFr: 'Ouganda', dialCode: '256' },
  { iso2: 'UZ', nameFr: 'Ouzbékistan', dialCode: '998' },
  { iso2: 'PK', nameFr: 'Pakistan', dialCode: '92' },
  { iso2: 'PW', nameFr: 'Palaos', dialCode: '680' },
  { iso2: 'PS', nameFr: 'Palestine', dialCode: '970' },
  { iso2: 'PA', nameFr: 'Panama', dialCode: '507' },
  { iso2: 'PG', nameFr: 'Papouasie-Nouvelle-Guinée', dialCode: '675' },
  { iso2: 'PY', nameFr: 'Paraguay', dialCode: '595' },
  { iso2: 'NL', nameFr: 'Pays-Bas', dialCode: '31' },
  { iso2: 'PE', nameFr: 'Pérou', dialCode: '51' },
  { iso2: 'PH', nameFr: 'Philippines', dialCode: '63' },
  { iso2: 'PL', nameFr: 'Pologne', dialCode: '48' },
  { iso2: 'PT', nameFr: 'Portugal', dialCode: '351' },
  { iso2: 'QA', nameFr: 'Qatar', dialCode: '974' },
  { iso2: 'DO', nameFr: 'République dominicaine', dialCode: '1' },
  { iso2: 'CZ', nameFr: 'République tchèque', dialCode: '420' },
  { iso2: 'RO', nameFr: 'Roumanie', dialCode: '40' },
  { iso2: 'GB', nameFr: 'Royaume-Uni', dialCode: '44' },
  { iso2: 'RU', nameFr: 'Russie', dialCode: '7' },
  { iso2: 'RW', nameFr: 'Rwanda', dialCode: '250' },
  { iso2: 'SM', nameFr: 'Saint-Marin', dialCode: '378' },
  { iso2: 'SV', nameFr: 'Salvador', dialCode: '503' },
  { iso2: 'WS', nameFr: 'Samoa', dialCode: '685' },
  { iso2: 'ST', nameFr: 'Sao Tomé-et-Principe', dialCode: '239' },
  { iso2: 'RS', nameFr: 'Serbie', dialCode: '381' },
  { iso2: 'SC', nameFr: 'Seychelles', dialCode: '248' },
  { iso2: 'SL', nameFr: 'Sierra Leone', dialCode: '232' },
  { iso2: 'SG', nameFr: 'Singapour', dialCode: '65' },
  { iso2: 'SK', nameFr: 'Slovaquie', dialCode: '421' },
  { iso2: 'SI', nameFr: 'Slovénie', dialCode: '386' },
  { iso2: 'SO', nameFr: 'Somalie', dialCode: '252' },
  { iso2: 'SD', nameFr: 'Soudan', dialCode: '249' },
  { iso2: 'SS', nameFr: 'Soudan du Sud', dialCode: '211' },
  { iso2: 'LK', nameFr: 'Sri Lanka', dialCode: '94' },
  { iso2: 'SE', nameFr: 'Suède', dialCode: '46' },
  { iso2: 'CH', nameFr: 'Suisse', dialCode: '41' },
  { iso2: 'SR', nameFr: 'Suriname', dialCode: '597' },
  { iso2: 'SY', nameFr: 'Syrie', dialCode: '963' },
  { iso2: 'TJ', nameFr: 'Tadjikistan', dialCode: '992' },
  { iso2: 'TW', nameFr: 'Taïwan', dialCode: '886' },
  { iso2: 'TZ', nameFr: 'Tanzanie', dialCode: '255' },
  { iso2: 'TD', nameFr: 'Tchad', dialCode: '235' },
  { iso2: 'TH', nameFr: 'Thaïlande', dialCode: '66' },
  { iso2: 'TL', nameFr: 'Timor oriental', dialCode: '670' },
  { iso2: 'TG', nameFr: 'Togo', dialCode: '228' },
  { iso2: 'TO', nameFr: 'Tonga', dialCode: '676' },
  { iso2: 'TT', nameFr: 'Trinité-et-Tobago', dialCode: '1' },
  { iso2: 'TN', nameFr: 'Tunisie', dialCode: '216' },
  { iso2: 'TM', nameFr: 'Turkménistan', dialCode: '993' },
  { iso2: 'TR', nameFr: 'Turquie', dialCode: '90' },
  { iso2: 'TV', nameFr: 'Tuvalu', dialCode: '688' },
  { iso2: 'UA', nameFr: 'Ukraine', dialCode: '380' },
  { iso2: 'UY', nameFr: 'Uruguay', dialCode: '598' },
  { iso2: 'VU', nameFr: 'Vanuatu', dialCode: '678' },
  { iso2: 'VA', nameFr: 'Vatican', dialCode: '379' },
  { iso2: 'VE', nameFr: 'Venezuela', dialCode: '58' },
  { iso2: 'VN', nameFr: 'Vietnam', dialCode: '84' },
  { iso2: 'YE', nameFr: 'Yémen', dialCode: '967' },
  { iso2: 'ZM', nameFr: 'Zambie', dialCode: '260' },
  { iso2: 'ZW', nameFr: 'Zimbabwe', dialCode: '263' },
];

/** Regional-indicator flag emoji from an ISO 3166-1 alpha-2 code. */
export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

/**
 * Longest dial-code-prefix match for an E.164-ish value (e.g.
 * "+221771234567" → Sénégal). Falls back to Sénégal (the app's home
 * market) for an empty value or one with no match.
 */
export function findCountryByDialPrefix(value: string): CountryDialCode {
  const senegal = COUNTRY_DIAL_CODES[0]!;
  if (!value.startsWith('+')) return senegal;
  const digits = value.slice(1);
  const byLength = [...COUNTRY_DIAL_CODES].sort((a, b) => b.dialCode.length - a.dialCode.length);
  return byLength.find((c) => digits.startsWith(c.dialCode)) ?? senegal;
}
